#build, test, style, deploy, bot

stages:
  - build
  - style

build_project:
  stage: build
  tags:
    - build
  script:
    - cd src/grep && make s21_grep
    - cd ../cat && make s21_cat
  artifacts:
    expire_in: "30 days"
    paths:
      - src/

test-style_project:
  stage: test_style
  tags:
    - style
  script:
    - ls