#build, test, style, deploy, bot #

stages:
  - build
  - style
  - test
  - deploy
  - notify

build_project:
  stage: build
  tags:
    - build
  script:
    - cd src/grep && make s21_grep && mv s21_grep ../build
    - cd ../cat && make s21_cat && mv s21_cat ../build
  artifacts:
    expire_in: "30 days"
    paths:
      - "src/build/"

test-style_project:
  stage: style
  tags:
    - style
  script:
    - cd src/
    - clang-format -n -Werror grep/s21_grep.*
    - clang-format -n -Werror cat/s21_cat.*

test_project:
  stage: test
  tags:
    - test
  script:
    - cd src/grep && make test
    - cd ../cat && make test

notify_bot:
  stage: notify
  needs: [build_project, test-style_project, test_project]
  tags:
    - bot
  script:
    - ./src/bot.sh
  when: always # Этот этап будет выполнен всегда, независимо от статуса pipeline


deploy_project:
  stage: deploy
  tags:
    - deploy
  script:
    - ./src/script.sh
  when: manual

notify_bot2:
  stage: notify
  tags:
    - bot
  needs: [deploy_project]
  script:
    - ./src/bot.sh
  when: always
  