#build, test, style, deploy, bot #

stages:
  - build
  - style
  - test

build_project:
  stage: build
  tags:
    - build
  script:
    - cd src/grep && make s21_grep
    - cd ../cat && make s21_cat
  artifacts:
    expire_in: "30 days"
    paths:
      - src/

test-style_project:
  stage: style
  tags:
    - style
  script:
    - cd src/
    - clang-format -n -Werror grep/s21_grep.*
    - clang-format -n -Werror cat/s21_cat.*

test_project:
  stage: test
  tags:
    - test
  script:
    - cd src/grep && make test
    - cd ../cat && make test

    
